# Jekyll configuration

name: TwoFactor Assimilation
description: Tech Enthusiast

# Url is currently only used only for the RSS feed in feed.xml
url: http://t04glovern.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

social:
  github: t04glovern
  stackoverflow: 5443325
  linkedin: glovernathan
  codepen: t04glovern
  instagram: nathanglove
  lastfm: t04glovern
  rss: feed.xml

author:
  full_name: Nathan Glover
  email_md5: 3f588f12eca6a2e82161a1da2451fe89
  bio: |
    Nathan Glover is a passionate technology enthusiast with a strong
    understanding of Windows Server 2012 / Hyper-V and Windows Operating
    system support. He has an eagerness to learn new things and generally
    spends most of his freetime building up his brain with different concepts.

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-71336829-1
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: t04glovern
comments: true

permalink: /:year/:month/:title
gems: [jekyll-paginate]
# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 10

#highlighter: pygments
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
